### PR TITLE
Add support for Android downloads

### PR DESCRIPTION
**Pull request by million1156**

### CODE REVIEW

**Comment by million1156** [comment]
NOTE: I don't know if the support for the new Gitea/Forgejo downloads work yet.. Some very smart individual blocked all inbound API requests to the git server, so I can't test my changes on anything but `suyu.dev`, but it *should* work!

**Comment by not-nullptr** [comment]
testing in production? really lol? go ask whoever hosts the git server to fix their end, i'll merge once we can confirm this works

**Comment by Zekerocks011** [comment]
I would recommend changing the p tag at the end of the file to include an underline or something like the code below to make the click here text more obvious

This code here makes the "click here" text bold, makes it the switch blue colour, and when you hover it transitions to the red switch colour

`	<p class="max-w-[36rem] text-lg leading-relaxed text-[#A6A5A7]">
		Your download should start shortly. If it doesn't, <a class="transition hover:text-[#f94d4d] font-bold text-[#60c7e9]"
			href="https://gitlab.suyu.dev/suyu/suyu/releases">click here</a
		>
        instead.
	</p>`

**Comment by million1156** [comment]
> testing in production? really lol? go ask whoever hosts the git server to fix their end, i'll merge once we can confirm this works

@not-nullptr , I was finally able to test this. There was an issue with how it returned the release but I've confirmed it to be working (works for Android, PC, Mac, & Linux).

You may merge it now :)

**Comment by not-nullptr** [comment]
ugh merge conflicts. give me a few mins

**Pull request merged**
